<?php

use App\Tag;
use Illuminate\Database\Seeder;


class TagTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    { 
    	$tag1 = new Tag;
    	$tag1 -> tname = '瓜子';
        $tag1 -> cate_id = rand(1,10);
    	$tag1 -> save();
        $tag2 = new Tag;
        $tag2 -> tname = '花生';
        $tag2 -> cate_id = rand(1,10);
        $tag2 -> save();
        $tag3 = new Tag;
        $tag3 -> tname = '栗子';
        $tag3 -> cate_id = rand(1,10);
        $tag3 -> save();
        $tag4 = new Tag;
        $tag4 -> tname = '坚果';
        $tag4 -> cate_id = rand(1,10);    
        $tag4 -> save();
        $tag5 = new Tag;
        $tag5 -> tname = '豆类';
        $tag5 -> cate_id = rand(1,10);   
        $tag5 -> save();
        $tag6 = new Tag;
        $tag6 -> tname = '饼干';
        $tag6 -> cate_id = rand(1,10);
        $tag6 -> save();
        $tag7 = new Tag;
        $tag7 -> tname = '威化饼';
        $tag7 -> cate_id = rand(1,10);
        $tag7 -> save();
        $tag8 = new Tag;
        $tag8 -> tname = '曲奇';
        $tag8 -> cate_id = rand(1,10);
        $tag8 -> save();
        $tag9 = new Tag;
        $tag9 -> tname = '苏打';
        $tag9 -> cate_id = rand(1,10);
        $tag9 -> save();
        $tag10 = new Tag;
        $tag10 -> tname = '夹心饼干';
        $tag10 -> cate_id = rand(1,10);
        $tag10 -> save();
        $tag11 = new Tag;
        $tag11 -> tname = '涂层饼干';
        $tag11 -> cate_id = rand(1,10);
        $tag11 -> save();
        $tag12 = new Tag;
        $tag12 -> tname = '中式糕点';
        $tag12 -> cate_id = rand(1,10);
        $tag12 -> save();
        $tag13 = new Tag;
        $tag13 -> tname = '蛋卷';
        $tag13 -> cate_id = rand(1,10);
        $tag13 -> save();
        $tag14 = new Tag;
        $tag14 -> tname = '酥';
        $tag14 -> cate_id = rand(1,10);
        $tag14 -> save();
        $tag15 = new Tag;
        $tag15 -> tname = '松塔';
        $tag15 -> cate_id = rand(1,10);
        $tag15 -> save();
        $tag16 = new Tag;
        $tag16 -> tname = '糕点';
        $tag16 -> cate_id = rand(1,10);
        $tag16 -> save();
        $tag17 = new Tag;
        $tag17 -> tname = '蛋糕';
        $tag17 -> cate_id = rand(1,10);
        $tag17 -> save();
        $tag18 = new Tag;
        $tag18 -> tname = '面包';
        $tag18 -> cate_id = rand(1,10);
        $tag18 -> save();
        $tag19 = new Tag;
        $tag19 -> tname = '软糖';         
        $tag19 -> cate_id = rand(1,10);
        $tag19 -> save();
        $tag20 = new Tag; 
        $tag20 -> tname = '硬糖';
        $tag20 -> cate_id = rand(1,10);
        $tag20 -> save();
        $tag21 = new Tag;
        $tag21 -> tname = '棒棒糖';
        $tag21 -> cate_id = rand(1,10);
        $tag21 -> save();
        $tag22 = new Tag;
        $tag22 -> tname = '含片';
        $tag22 -> cate_id = rand(1,10);
        $tag22 -> save();
        $tag23 = new Tag;
        $tag23 -> tname = '果冻布丁';
        $tag23 -> cate_id = rand(1,10);
        $tag23 -> save();
        $tag24 = new Tag;
        $tag24 -> tname = '龟苓膏';
        $tag24 -> cate_id = rand(1,10);
        $tag24 -> save();
        $tag25 = new Tag;
        $tag25 -> tname = '巧克力';
        $tag25 -> cate_id = rand(1,10);
        $tag25 -> save();
        $tag26 = new Tag;
        $tag26 -> tname = '玩具';
        $tag26 -> cate_id = rand(1,10);
        $tag26 -> save();    
        $tag27 = new Tag;
        $tag27 -> tname = '梅类';
        $tag27 -> cate_id = rand(1,10);
        $tag27 -> save();
        $tag28 = new Tag;
        $tag28 -> tname = '枣类';
        $tag28 -> cate_id = rand(1,10);
        $tag28 -> save();
        $tag29 = new Tag;
        $tag29 -> tname = '葡萄干';
        $tag29 -> cate_id = rand(1,10);
        $tag29 -> save();
        $tag30 = new Tag;
        $tag30 -> tname = '山楂类';
        $tag30 -> cate_id = rand(1,10);
        $tag30 -> save();
        $tag31 = new Tag;
        $tag31 -> tname = '水果干';
        $tag31 -> cate_id = rand(1,10);
        $tag31 -> save();
        $tag32 = new Tag;
        $tag32 -> tname = '芒果类';
        $tag32 -> cate_id = rand(1,10);
        $tag32 -> save();
        $tag33 = new Tag;
        $tag33 -> tname = '果干';
        $tag33 -> cate_id = rand(1,10);
        $tag33 -> save();
        $tag34 = new Tag;
        $tag34 -> tname = '蔬菜干';
        $tag34 -> cate_id = rand(1,10);
        $tag34 -> save();
        $tag35 = new Tag;
        $tag35 -> tname = '枣';
        $tag35 -> cate_id = rand(1,10);
        $tag35 -> save();
        $tag36 = new Tag;
        $tag36 -> tname = '鱼类';
        $tag36 -> cate_id = rand(1,10);
        $tag36 -> save();
        $tag37 = new Tag;
        $tag37 -> tname = '海苔类';
        $tag37 -> cate_id = rand(1,10);
        $tag37 -> save();
        $tag38 = new Tag;
        $tag38 -> tname = '鱿鱼类';
        $tag38 -> cate_id = rand(1,10);
        $tag38 -> save();
        $tag39 = new Tag;
        $tag39 -> tname = '锅巴';
        $tag39 -> cate_id = rand(1,10);
        $tag39 -> save();
        $tag40 = new Tag;
        $tag40 -> tname = '米饼';
        $tag40 -> cate_id = rand(1,10);
        $tag40 -> save();
        $tag41 = new Tag;
        $tag41 -> tname = '米卷类';
        $tag41 -> cate_id = rand(1,10);
        $tag41 -> save();
        $tag42 = new Tag;
        $tag42 -> tname = '虾片类';
        $tag42 -> cate_id = rand(1,10);
        $tag42 -> save();
        $tag43 = new Tag;
        $tag43 -> tname = '脆脆条';
        $tag43 -> cate_id = rand(1,10);
        $tag43 -> save();
        $tag44 = new Tag;
        $tag44 -> tname = '尖角酥';
        $tag44 -> cate_id = rand(1,10);
        $tag44 -> save();
        $tag45 = new Tag;
        $tag45 -> tname = '薯片类';
        $tag45 -> cate_id = rand(1,10);
        $tag45 -> save();
        $tag46 = new Tag;
        $tag46 -> tname = '爆米花';
        $tag46 -> cate_id = rand(1,10);
        $tag46 -> save();
        $tag47 = new Tag;
        $tag47 -> tname = '咖啡';
        $tag47 -> cate_id = rand(1,10);
        $tag47 -> save();
        $tag48 = new Tag;
        $tag48 -> tname = '奶茶冲饮';
        $tag48 -> cate_id = rand(1,10);
        $tag48 -> save();
        $tag49 = new Tag;
        $tag49 -> tname = '冲饮';
        $tag49 -> cate_id = rand(1,10);
        $tag49 -> save();
        $tag50 = new Tag;
        $tag50 -> tname = '花果茶';
        $tag50 -> cate_id = rand(1,10);
        $tag50 -> save(); 
        $tag51 = new Tag;
        $tag51 -> tname = '牛奶';
        $tag51 -> cate_id = rand(1,10);
        $tag51 -> save();
        $tag52 = new Tag;
        $tag52 -> tname = '罐头';
        $tag52 -> cate_id = rand(1,10);
        $tag52 -> save();
        $tag53 = new Tag;
        $tag53 -> tname = '饮料';
        $tag53 -> cate_id = rand(1,10);
        $tag53 -> save();
        $tag54 = new Tag;
        $tag54 -> tname = '啤酒';
        $tag54 -> cate_id = rand(1,10);
        $tag54 -> save();
        $tag55 = new Tag;
        $tag55 -> tname = '豆干';
        $tag55 -> cate_id = rand(1,10);
        $tag55 -> save();
        $tag56 = new Tag;
        $tag56 -> tname = '豆制品';
        $tag56 -> cate_id = rand(1,10);
        $tag56 -> save();
        $tag57 = new Tag;
        $tag57 -> tname = '菌';
        $tag57 -> cate_id = rand(1,10);
        $tag57 -> save();
        $tag58 = new Tag;
        $tag58 -> tname = '菇';
        $tag58 -> cate_id = rand(1,10);
        $tag58 -> save();
        $tag59 = new Tag;
        $tag59 -> tname = '肠';
        $tag59 -> cate_id = rand(1,10);
        $tag59 -> save();
        $tag60 = new Tag;
        $tag60 -> tname = '肠仔';
        $tag60 -> cate_id = rand(1,10);
        $tag60 -> save();
        $tag61 = new Tag;
        $tag61 -> tname = '蛋类制品';
        $tag61 -> cate_id = rand(1,10);
        $tag61 -> save();
        $tag62 = new Tag;
        $tag62 -> tname = '方便面';
        $tag62 -> cate_id = rand(1,10);
        $tag62 -> save();
        $tag63 = new Tag;
        $tag63 -> tname = '速食品';
        $tag63 -> cate_id = rand(1,10);
        $tag63 -> save();
        
    }
}
